config/routes.rb
Rails.application.routes.draw do

  post '/rate' => 'rater#create', :as => 'rate'
  resources :contacts
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  resources :links do
    get :autocomplete_link_streetaddress, :on => :collection
    get :autocomplete_link_regionaladdress, :on => :collection
    collection do
    match 'advanced_search' => 'links#advanced_search', via: [:get, :post], as: :advanced_search
    match 'result_page' => 'links#result_page', via: [:get, :post], as: :result_page
    end
    member do
        put "like", to: "links#upvote"
        put "dislike", to: "links#downvote"
    end
    resources :comments
  end

  root 'links#index'

end

app/models/link.rb
class Link < ActiveRecord::Base
	acts_as_votable
    belongs_to :user
    has_many :comments

    validates :name, :presence => true
    validates :streetaddress, :presence => true

    # add rating capability using ratyrate
    ratyrate_rateable 'cleanliness', 'noise_level', 'convenience', 'custome_design'

    def full_address
        [streetaddress, regionaladdress].compact.join(', ')
    end

    geocoded_by :full_address
    after_validation :geocode, :if => :streetaddress_changed?
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  # For autocomplete feature
  autocomplete :link, :streetaddress, :full => true
  autocomplete :link, :regionaladdress, :full => true

  # adding before_filter to control who can do things like edit or delete
  #before_filter :authenticate_user!, :only => [:index, :show, :advanced_search]

  before_action :authorized_user, only: [:new, :create, :edit, :update, :destroy]
  before_action :set_link, only: [:show, :edit, :update, :destroy]



  def index
    @q = Link.ransack(@temp)
    @links = @q.result(distinct: true)

    @topfive = Link.order('averageprice').limit(5)
    # Responses with list of apartment when queries with json for autocomplete.
    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @links.to_json }
    end
  end

  def rate
        @link = Link.find(params[:id])

  end


  def result_page
    @q = Link.ransack(params[:q])
    @links = @q.result(distinct: true)


  end

  def advanced_search
    @q = Link.ransack(params[:q])
    @links = @q.result(distinct: true)
    #@q.build_condition
    #@q.build_sort
  end

  # GET /links/1
  # GET /links/1.json
  def show
  end

  # GET /links/new
  def new
    @link = current_user.links.build # using devise helper "current_user"
  end

  # GET /links/1/edit
  def edit
  end

  # POST /links
  # POST /links.json
  def create
    @link = current_user.links.build(link_params) # using devise helper "current_user"
    logger.debug " DEBUG :::::::: #{link_params.to_json}"
    respond_to do |format|
      if @link.save
        format.html { redirect_to @link, notice: 'Link was successfully created.' }
        format.json { render :show, status: :created, location: @link }
      else
        format.html { render :new }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /links/1
  # PATCH/PUT /links/1.json
  def update
    respond_to do |format|
      if @link.update(link_params)
        format.html { redirect_to @link, notice: 'Link was successfully updated.' }
        format.json { render :show, status: :ok, location: @link }
      else
        format.html { render :edit }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /links/1
  # DELETE /links/1.json
  def destroy
    @link.destroy
    respond_to do |format|
      format.html { redirect_to links_url, notice: 'Link was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def upvote
    @link = Link.find(params[:id])
    @link.upvote_by current_user
    redirect_to :back
  end

  def downvote
    @link = Link.find(params[:id])
    @link.downvote_by current_user
    redirect_to :back
  end

  private

    # to stop user from editing url that doesn't belong to them
    def authorized_user
      if current_user.is_admin?
      else
        @link = current_user.links.find_by(id: params[:id])
        redirect_to links_path, notice: "Not authorized to edit this link" if @link.nil?
      end
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_link
      @link = Link.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def link_params
      params.require(:link).permit(:name, :streetaddress, :regionaladdress, :averageprice, :built, :floors, :suites, :bedroom => [], :amenities => [])
    end

end

app/helpers/links_helper.rb
module LinksHelper
end

app/views/links/_form.html.erb
<!-- <div class="container" id="contentcontainer"> -->
<%= form_for(@link) do |f| %>
  <% if @link.errors.any? %>
    <div id="error_explanation">

      <ul>
      <% @link.errors.full_messages.each do |message| %>
        <li id="ListA"><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="wrap">
    <div class="field">
      <%= f.label :name , :class => "add_info"%><br>
      <%= f.text_field :name %><br><br>
    
      <%= f.label :streetaddress, "Street Address", :class => "add_info" %><br>
      <%= f.text_field :streetaddress %><br><br>

      <%= f.label :regionaladdress, "Region",:class => "add_info" %><br>
      <%= f.text_field :regionaladdress %><br><br>

      <%= f.label :averageprice, "Average Price", :class => "add_info" %><br>
      <%= f.text_field :averageprice %><br><br>      

      <%= f.label :built , :class => "add_info" %><br>
      <%= f.text_field :built %><br><br>
    
      <%= f.label :floors , :class => "add_info"%><br>
      <%= f.text_field :floors %><br><br>
 
      <%= f.label :suites , :class => "add_info" %><br>
      <%= f.text_field :suites %><br>
    </div>

    <div class="field2">
      <%= f.label :bedroom , :class => "add_info" %><br>
      <%= check_box_tag 'link[bedroom][]', "studio"%>
      <%= f.label :bedroom, 'Studio'  %><br>
      <%= check_box_tag 'link[bedroom][]', "1bdr"%>
      <%= f.label :bedroom, '1 Bedroom' %><br>
      <%= check_box_tag 'link[bedroom][]', "2bdr"%>
      <%= f.label :bedroom, '2 Bedroom'%><br>
      <%= check_box_tag 'link[bedroom][]', "3bdr"%>  
      <%= f.label :bedroom, '3 Bedroom' %><br><br>
  
      <%= f.label :amenities , :class => "add_info" %><br>
      <%= check_box_tag 'link[amenities][]', "gym"%>
      <%= f.label :amenities, 'Gym'  %><br>
      <%= check_box_tag 'link[amenities][]', "pool"%>
      <%= f.label :amenities, 'Pool' %><br>
      <%= check_box_tag 'link[amenities][]', "sauna"%>
      <%= f.label :amenities, 'Sauna'%><br>
      <%= check_box_tag 'link[amenities][]', "hottub"%>   
      <%= f.label :amenities, 'Hottub' %><br>
    </div>
    <div style="clear: both;">
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
</div>

app/views/links/advanced_search.html.erb
<!-- Implements search feature using gem "Ransack" -->




  <!-- <!= Implements search feature using gem "Ransack" => -->
<div id = "preference" align='center'>

<div id="aligning">
  

<%= search_form_for @q, url: result_page_links_path, html: {method: :post, class: "search_form"} do |f| %>
  
  <br>
  <%= f.label :regionaladdress_cont, 'Region?' %>
  <%= f.autocomplete_field :regionaladdress_cont, autocomplete_link_regionaladdress_links_path, :size => 20, id: 'my_autocomplete_field' %>
<br>
  <%= f.label :averageprice_gteq, 'Price between' %>
  <%= f.text_field :averageprice_gteq %>
  <%= f.label :averageprice_lteq, 'and' %>
  <%= f.text_field :averageprice_lteq %>
<br>
  <br> 
  
  <%= f.submit 'Show Me Recomendations', class: 'search_submit' %>
  <button type="button" id = "advanced_search"><%= link_to 'Nah, Just get me simple search', result_page_links_path, {:style=>'color:black;', :class => "table_element"} %></button>

  
<% end %>
</div>
</div>
</div>






<script>
  $(document).ready(ready);
    $(document).on('page:load',ready);

    // table row to be clickable
    
    jQuery(function($) {
      $("tr[data-link]").click(function() {
        window.location = this.dataset.link
      });
    })
</script>

app/views/links/edit.html.erb
<div id ="center_aligner">
<h1>Editing Link</h1>

<%= render 'form' %>

<!-- # <%= link_to 'Show', @link %>  | -->
<%= button_to 'Back', @link, :class => "back1", :method => :get %>
</div>

app/views/links/index.html.erb
<!-- background main image -->
<!-- <img src="main.jpg" id="main-img"> -->
<!-- Implements search feature using gem "Ransack" -->
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>
<script src="jquery.quovolver.js"></script>
<p id="notice"><%= notice %></p>



<div class="outer">

<div class="middle">

  <div class="quotes">
      <blockquote>
        <p>Find out more about your <br>Apartment</p>
    </blockquote>
      <blockquote>
        <p>Talk more about your  <br>  Apartment</p>
    </blockquote>

	<h1 class="quotes">Find out more about your <br>Apartment</h1>
<!-- <h1 class="quotes">Talk more about your  <br>  Apartment</h1> -->

<div class="inner">
<div id="mainpage-searchbar">

  <!-- <!= Implements search feature using gem "Ransack" => -->

<%= search_form_for @q, url: result_page_links_path, html: {method: :post, class: "search_form"} do |f| %>
  <!--<%= f.label :name_or_address_cont, '     ' %>-->
  <br>
  <p>
    <button type="button" id = "advanced_search"><%= link_to 'Do you want our recommendations?', advanced_search_links_path, {:style=>'color:black;', :class => "table_element"}%></button>
    <%= f.autocomplete_field :name_or_streetaddress_or_regionaladdress_cont, autocomplete_link_streetaddress_links_path, :size => 70, id: 'my_autocomplete_field' %>
    <%= f.submit class: 'search_submit', id: 'advanced_search' %>
  </p>
  <br>
  
<% end %>


</div>
</div>
</div>
</div>
<br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>

<div id="resultmain">
<div id="titleoftop">
  

<h1>Top 5 Apartments</h1>
</div>
  <table id="result_table">
    <thead id="result_head">
      <tr>


        <th id='th1'>
          <h5>Region</h5>
        </th>
        <th id='th2'>
          <h5>Name</h5>
        </th>
        <th id='th3'>
          <h5>Averageprice</h5>
        </th>
        <th id='th4'>
          <h5>Rates</h5>
          <!-- <h5><%= sort_link @q, :rates, "Rates"%></h5> -->
        </th>
        <th id='th5'>
          <h5>Comments</h5>
          <!-- <h5><%= sort_link @q, :comments, "Comments"%></h5>-->
        </th>
      </tr>
    </thead>
    <tbody id="result_body">
      <% @topfive.each do |link| %>
      <tr class="<%= cycle('oddrow', 'evenrow') -%>" data-link="<%= link_path(link) %>">
        <td id='td1'><h5><%= link.regionaladdress %></h5></td>
        <td id='td2'><h4><%= link.name %></h4><p><%= link.streetaddress %></p></td>
        <td id='td3'><h5><%= link.averageprice %></h5></td>
        <td id='td4'><p><%= link.get_upvotes.size %></p></td>
        <td id='td5'><p><%= link.comments.count %><p></td>

      </tr>

      <% end %>
    </tbody>
  </table>
</div>
<script type="text/javascript">
    var ready;

    ready = function(){

      $('#my_autocomplete_field').bind('railsAutocomplete.select', function(event, data){
  		/* Do something when choice is clicked */
  	   });

  
  // Call Quovolver on the '.quotes' object
      $('#demo-one .quotes').quovolver();
  

    $(document).ready(ready);
    $(document).on('page:load',ready);
</script>

app/views/links/new.html.erb
<div id ="center_aligner">
<h1 class= "apt-name">New Apartment</h1>

<%= render 'form' %>

<%= button_to 'Back', result_page_links_path , :class => "back1", :method => :get %>
</div>

app/views/links/result_page.html.erb
<!-- Implements search feature using gem "Ransack" -->
<div id="mainpage-searchbar">


  <!-- <!= Implements search feature using gem "Ransack" => -->

<%= search_form_for @q, url: result_page_links_path, html: {method: :post, class: "search_form"} do |f| %>
  <!--<%= f.label :name_or_address_cont, '     ' %>-->
  <br>
  <p><button type="button" id = "advanced_search"><%= link_to 'Do you want our recommendation?', advanced_search_links_path, {:style=>'color:black;', :class => "table_element"} %></button>
  <%= f.autocomplete_field :name_or_streetaddress_or_regionaladdress_cont, autocomplete_link_streetaddress_links_path, :size => 100, id: 'my_autocomplete_field' %> <%= f.submit class: 'search_submit' %> </p>

  
<% end %>
</div>

<!-- <div align = "center" id="resultmain"> -->
<div id="resultmain">
  <table id="result_table">
    <thead id="result_head">
      <tr>
        <th id='th1'>
          <h5>
            <%= sort_link @q, :name, "Region"%>
          </h5>
        </th>
        <th id='th2'>
          <h5>
            <%= sort_link @q, :name, "Name"%>
          </h5>
        </th>
        <th id='th3'>
          <h5>
            <%= sort_link @q, :averageprice, "Averageprice"%>
          </h5>
        </th>
        <th id='th4'>
          <h5>Rates</h5>
          <!-- <h5><%= sort_link @q, :rates, "Rates"%></h5> -->
        </th>
        <th id='th5'>
          <h5>Comments</h5>
          <!-- <h5><%= sort_link @q, :comments, "Comments"%></h5>-->
        </th>
      </tr>
    </thead>
    <tbody id="result_body">
      <% @links.each do |link| %>
      <tr class="<%= cycle('oddrow', 'evenrow') -%>" data-link="<%= link_path(link) %>">
        <td id='td1'><h5><%= link.regionaladdress %></h5></td>
        <td id='td2'><h4><%= link.name %></h4><p><%= link.streetaddress %></p></td>
        <td id='td3'><h5><%= link.averageprice %></h5></td>
        <td id='td4'><p><%= link.get_upvotes.size %></p></td>
        <td id='td5'><p><%= link.comments.count %><p></td>

      </tr>

      <% end %>
    </tbody>
  </table>
  </div>



<script>
  $(document).ready(ready);
    $(document).on('page:load',ready);

    // table row to be clickable
    
    jQuery(function($) {
      $("tr[data-link]").click(function() {
        window.location = this.dataset.link
      });
    })
</script>

app/views/links/show.html.erb
<!-- <p id="notice"><%= notice %></p> -->

<div class="container" id="showmain">
  
  <div id="showinfo" class="col-xs-8">
    <h1><%= @link.name %></h1>
    <hr>
    <p><%= @link.streetaddress %>, <%= @link.regionaladdress %></p>
    <ul id="showul">
      <li><p>Built: <%= @link.built %></p></li>
      <li><p>Suites: <%= @link.suites %></p></li>
      <li><p>Floors: <%= @link.floors %></p></li>
    </ul>

    <table>
      <tr>
        <div id="suitestypes">
          <td><p>Suites Types:</p></td>
          <td>
            <ul>
              <% @link.bedroom.each do | room |%>
                <li>
                  <p><%= room %></p>
                </li>
              <%end%>
            </ul>
          </td>
        </div>
        <div id="amentypes">
          <td><p>Amenities:</p></td>
          <td>
            <ul>
              <% @link.amenities.each do | amen |%>
                <li>
                  <p><%= amen %></p>
                </li>
              <%end%>
            </ul>
          </td>
        </div>

      </tr>
    </table>
    <br><br><br>
    <%= link_to 'Edit', edit_link_path(@link) %> |
    <%= link_to 'Back', result_page_links_path %>
  </div>
  
  <div id="showmap" class="col-xs-4">
    <%= image_tag "http://maps.google.com/maps/api/staticmap?size=450x300&sensor=false&zoom=16&markers=#{@link.latitude}%2C#{@link.longitude}" %>
  </div>

  
</div>
<div id="ratingres" class="container">

  <div class="readonly-star">
<!-- using the Ratyrate Helper in Views -->
    <div class="row">
      <div class="small-2 large-3 columns">
        
          <div class="col-xs-2">Cleanliness: <%= rating_for @link, "cleanliness", readOnly: true, disable_after_rate: true, imdb_avg: true %></div>
          <div class="col-xs-2">Noise Level: <%= rating_for @link, "noise_level", disable_after_rate: true, imdb_avg: true %></div>
          <div class="col-xs-2">Convenience: <%= rating_for @link, "convenience", disable_after_rate: true, imdb_avg: true %></div>
          
          <div class="btn-group" class="col-xs-4">
            <div id="likebutton" class="col-xs-3">
              <%= link_to like_link_path(@link), method: :put, class: "btn btn-default btn-sm" do %>
              <span class="glyphicon glyphicon-chevron-up">
              Like
              </span>
              <% end %>
            </div>

            <div id="hatebutton" class="col-xs-3">
              <%= link_to dislike_link_path(@link), method: :put, class: "btn btn-default btn-sm" do %>
              <span class="glyphicon glyphicon-chevron-down">
              Dislike
              </span>
              <% end %>
            </div>

      
      
          </div>
        
      </div>
    </div>
<!-- end of ratyrate helper view -->
  </div>
  <div id="buttoncent">
    <%= button_to "Rate this apartment", new_link_comment_path(@link), :class => "button", :method => :get  %>
  </div>
</div>

<div id="commentsarea" class="container">
  <div>
  <h4>
    <%= @link.comments.count %> Comments
  </h4>
  <hr>
 
  <p><%= render :partial => @link.comments %></p>
 

  </div>
</div>



<script type="text/javascript">

ready = function(){

$(".readonly-star .star").each(function() {
$(this).raty('set', { readOnly: true });
});

};

$(document).ready(ready);
$(document).on('page:load',ready);
</script>